eval "$(starship init zsh)"

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
FPATH=/opt/homebrew/share/zsh-completions:$FPATH
FPATH=/opt/homebrew/share/zsh/site-functions:$FPATH

# Load fzf if available
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Version managers (uncomment the one you want to use)
# Both can be installed, but enabling both simultaneously may cause PATH conflicts
# eval "$(anyenv init -)"
eval "$(mise activate zsh)"

