#!/bin/bash

readonly PREV_HEAD=$1
readonly CURRENT_HEAD=$2
readonly CHECKOUT_TYPE=$3

IGNORED=("develop" "master" "main" "staging" "staging2")
IGNORED_PREFIX=("release" "feedback" "hotfix")
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

containsElement() {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

startWith() {
  local e
  for e in "${@:2}"; do [[ "$1" == "$e"* ]] && return 0; done
  return 1
}

if [ ${CHECKOUT_TYPE} -ne 1 ]; then
  exit 0
fi

if [ "${PREV_HEAD}" == "null-ref" ]; then
  exit 0
fi

if containsElement "${BRANCH_NAME}" "${IGNORED[@]}"; then
  exit 0
fi

if startWith "${BRANCH_NAME}" "${IGNORED_PREFIX[@]}"; then
  exit 0
fi

NUM_CHECKOUTS=$(git reflog show "${BRANCH_NAME}" 2>/dev/null | wc -l)

if [ "${PREV_HEAD}" == "${CURRENT_HEAD}" ] && [ "${NUM_CHECKOUTS}" -eq 1 ]; then
  git commit --allow-empty -m "Work has started on the ${BRANCH_NAME}"
fi
